stages:
    - test
test:
  stage: test
  image: registry.gitlab.com/sertiscorp/mle/edge/jetsonlpr
  script:
    - nvcc --version
    - echo $PATH
    - echo $LD_LIBRARY_PATH
    - pip3 install -r requirements.txt
    - python3 unit_test.py
    - python3 int_test.py


