# choose from ['tvm', 'mxnet', 'jet_inference']
mode: 'tvm'

# path to directory with tvm opt model
# only needed for when mode is 'tvm'
model_file_dir: 'models'

# region of lp ('eu' or 'us')
region: 'eu'

# video camera number
video_camera: '0'

# between 'llvm' and 'cuda'
target: 'cuda'

# OpenALPR repo
OpenALPR: '/home/fourth/Desktop/repo/openalpr'